### ISSUE TITLE
Add Data Paper Link to Source Section

### ISSUE THREAD

**Issue by sepandhaghighi** [ECSIM/pem-dataset1#12]
#### Description
Add data paper link to source section

**Comment by sepandhaghighi** [comment]
@sarminh @kasraaskari
Done!
Please double check and if everything is OK then close this issue ;-)

**Comment by sarminh** [comment]
Is the citation style of data paper correct? First author's name is reverse but others author's name are different.

**Comment by sepandhaghighi** [comment]
> Is the citation style of data paper correct? First author's name is reverse but others author's name are different.

You are right, it is strange!!!
But I copy it from chemarxiv website, chemarxiv support different citation styles. Please check cite section in the preprint page, choose a proper one and paste it here ;-)

**Comment by sarminh** [comment]
@sepandhaghighi S. Hamidi, S. Haghighi, K. Askari, Dataset of Standard Tests of Nafion 112 Membrane and Membrane Electrode Assembly (MEA) Activation Tests of Proton Exchange Membrane (PEM) Fuel Cell, ChemRxiv, (2020). doi:10.26434/chemrxiv.11902023.v1.

**Comment by sepandhaghighi** [comment]
@sarminh @kasraaskari Is it okay now?

**Comment by kasraaskari** [comment]
> @sarminh @kasraaskari Is it okay ?

I think it's okay.
