### ISSUE TITLE
Add Unit to Tables

### ISSUE THREAD

**Issue by sepandhaghighi** [ECSIM/pem-dataset1#3]
#### Description
Update unit of these parameters : 
1. OCV : mV
2. MPD : mW/cm2
3. i at 0.5V : mA/cm2
4. i at 0.3V : mA/cm2
5. RH : %

**Comment by sepandhaghighi** [comment]
> #### Description
> Update unit of these parameters :
> 
> 1. OCV : mV
> 2. MPD : mW/cm2
> 3. i at 0.5V : mA/cm2
> 4. i at 0.3V : mA/cm2
> 5. RH : %

@sarminh @kasraaskari 
Please double check these units and inform me, then I will update tables ;-)

**Comment by sarminh** [comment]
Thank you @sepandhaghighi . All is correct and ready to update tables.

**Comment by sepandhaghighi** [comment]
@sarminh @kasraaskari 
And also check abbreviations  : 
1. OCV : Open circuit voltage
2. MPD : Maximum power density 
3. i at 0.5V : Current density
4. i at 0.3V : Current density 
5. RH : Relative humidity
6. R : ??? Resistor

**Comment by sarminh** [comment]
Internal resistance or high frequency resistance?  @kasraaskari

**Comment by kasraaskari** [comment]
OCV : mV
MPD : mW/cm2
i at 0.5V : mA/cm2
i at 0.3V : mA/cm2
RH : %

All of the units are correct !
@sepandhaghighi

**Comment by kasraaskari** [comment]
OCV : Open circuit voltage
MPD : Maximum power density
i at 0.5V : Current density at 0.5V
i at 0.3V : Current density at 0.3V
RH : Relative humidity
R : High Frequency Resistance

 Abbreviations !
@sepandhaghighi

**Comment by sepandhaghighi** [comment]
@sarminh 
Done!
Please double check and if there is no more problem, close the issue.
