### ISSUE TITLE
Missing Amounts From Some Polarization Data

### ISSUE THREAD

**Issue by sarminh** [ECSIM/pem-dataset1#5]
#### Description 
Please check all Polarization curves at activation MEA file to find empties in the tables.

**Comment by kasraaskari** [comment]
I did it 
[PEMFC Activation Process Experiments.docx](https://github.com/ECSIM/pem-dataset1/files/4047787/PEMFC.Activation.Process.Experiments.docx)
@sarminh

**Comment by sarminh** [comment]
Thanks a lot.

**Comment by sarminh** [comment]
Done.

**Comment by sarminh** [comment]
@sepandhaghighi please double check and if there is no more problem in tables, close the issue.

**Comment by sarminh** [comment]
@kasraaskari Please double check and if there is no more problem in tables, close the issue.

**Comment by kasraaskari** [comment]
@sarminh 
I extracted most of the missing data from the polarization plots.
Still some of them are not actual.
[PEMFC Activation Process Experiments.docx](https://github.com/ECSIM/pem-dataset1/files/4116946/PEMFC.Activation.Process.Experiments.docx)

**Comment by sarminh** [comment]
@kasraaskari those are fine, thanks. I’ll put the tables in NAME files tomorrow.

**Comment by sarminh** [comment]
@sepandhaghighi table of details added to cycling potential data file, please edit configuration of the tables. 



[Tables.zip](https://github.com/ECSIM/pem-dataset1/files/4121391/Tables.zip)

**Comment by sepandhaghighi** [comment]
> @sepandhaghighi table of details added to cycling potential data file, please edit configuration of the tables.
> 
> [Tables.zip](https://github.com/ECSIM/pem-dataset1/files/4121391/Tables.zip)

Thanks for your effort ;-)
I will work on this issue in next few days

**Comment by sepandhaghighi** [comment]
@sarminh 
Done!
Please double check and if there is no more problem, close the issue.
