### ISSUE TITLE
Set Index Description

### ISSUE THREAD

**Issue by sepandhaghighi** [ECSIM/pem-dataset1#7]
#### Description
Add set index description to files

**Comment by sarminh** [comment]
Done.

**Comment by sarminh** [comment]
@kasraaskari Please write description protocol overview and mention the reference.

**Comment by kasraaskari** [comment]
@sarminh 
''Membrane Electrode Assembly Activation Procedure,'' (APRIL 4, 2013) Retrieved from https://fuelcellsetc.com/2013/04/membrane-electrode-assembly-mea-activation-procedures/

[Membrane Electrode Assembly Activation Procedure.docx](https://github.com/ECSIM/pem-dataset1/files/4111677/Membrane.Electrode.Assembly.Activation.Procedure.docx)

**Comment by sarminh** [comment]
@sepandhaghighi Where should we write additional information about MEA avtication protocol?

**Comment by sepandhaghighi** [comment]
> @sepandhaghighi Where should we write additional information about MEA avtication protocol?

I will add this information in a new `Markdown` file

**Comment by sepandhaghighi** [comment]
@sarminh
Done!
Please double check and if everything is OK then close this issue ;-)

[README.md](https://github.com/ECSIM/pem-dataset1/blob/master/README.md)
[MEA.md](https://github.com/ECSIM/pem-dataset1/blob/master/MEA.md)

**Comment by sarminh** [comment]
Everything is fine.
