### ISSUE TITLE
Data Paper

### ISSUE THREAD

**Issue by sarminh** [ECSIM/pem-dataset1#8]
#### Description
@sepandhaghighi @kasraaskari Please check out the data paper and comment. 
[Dataset of standard tests of Nafion 112 membrane and Membrane Electrode Assembly.pdf](https://github.com/ECSIM/pem-dataset1/files/4121514/Dataset.of.standard.tests.of.Nafion.112.membrane.and.Membrane.Electrode.Assembly.pdf)

**Comment by sepandhaghighi** [comment]
Thanks for your effort 💯 

My comments : 
1. We should mention somewhere in the data paper that this dataset published under **CC BY 4.0** license
2. **Reported Data** title should move to next page
3. We should avoid from [chartjunk](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4161295/), I think **Figure(9-2)**, **Figure(10-2)** and **Figure(4-2)** should be removed or reformatted 
4. **Figure(6-2)** has wrong caption position
5. All tables header should have unit
6. `Repository of PEMFC reported dataset contribute to ECSIM/pemdataset1 development by creating an account on GitHub`, this sentence is vague!!

**Comment by sarminh** [comment]
@sepandhaghighi Thanks for your comments. All mentioned cases except third case, was edited. I need more time to work on charts issue.

**Comment by sepandhaghighi** [comment]
@sarminh Thanks for your effort ;-)
